/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estagiosupervisionado.View;

import estagiosupervisionado.Commons.Entities.Funcionario;
import estagiosupervisionado.Commons.Entities.Ponto;
import estagiosupervisionado.Model.daos.FuncionarioDAO;
import estagiosupervisionado.Model.daos.PontoDAO;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.table.DefaultTableModel;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.sql.Date;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import estagiosupervisionado.Controller.Geral;

/**
 *
 * @author Matheus Lima
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Funcionario funcionarioLogado;
    private Date diaHoje;
    private Ponto pontoAtual;
    private ArrayList<Ponto> listaPontos;
    
    public TelaPrincipal(UUID id) {
        initComponents();
        
        setLocationRelativeTo(this);
        
        diaHoje = Date.valueOf(LocalDate.now());

        if(id != null){
            funcionarioLogado = new FuncionarioDAO().get(id);
            listaPontos = new PontoDAO().getAll(id);
            
            atualizaTabela(id);
            getPontoAtual();
            atualizaLabels();
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegistrarPonto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelSaida1 = new javax.swing.JLabel();
        jLabelEntrada1 = new javax.swing.JLabel();
        jLabelEntrada2 = new javax.swing.JLabel();
        jLabelSaida2 = new javax.swing.JLabel();
        jLabelDiaAtual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dia", "Entrada1", "Saida 1", "Entrada 2", "Saida 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Holerite");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonRegistrarPonto.setText("Registrar Ponto");
        jButtonRegistrarPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPontoActionPerformed(evt);
            }
        });

        jLabelSaida1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSaida1.setText("Saida1: ");

        jLabelEntrada1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEntrada1.setText("Entrada1: ");

        jLabelEntrada2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEntrada2.setText("Entrada2: ");

        jLabelSaida2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSaida2.setText("Saida2: ");

        jLabelDiaAtual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDiaAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDiaAtual.setText("14/11/2021");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistrarPonto, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEntrada2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSaida2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDiaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSaida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEntrada1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDiaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSaida1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSaida2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrarPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPontoActionPerformed
        Geral.registraPonto(pontoAtual, funcionarioLogado, this);
        atualizaTabela(funcionarioLogado.getId());
        atualizaLabels();
    }//GEN-LAST:event_jButtonRegistrarPontoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal(null).setVisible(true);
            }
        });
    }
    
    private void adicionaNaTabela(Ponto ponto) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        String en1 = ponto.getEntrada1() == null ? null : ponto.getEntrada1().toString();
        String sa1 = ponto.getSaida1() == null ? null : ponto.getSaida1().toString();
        String en2 = ponto.getEntrada2() == null ? null : ponto.getEntrada2().toString();
        String sa2 = ponto.getSaida2() == null ? null : ponto.getSaida2().toString();
        
        model.addRow(new Object[]{ ponto.getDia().toString() , en1, sa1, en2, sa2 });

    }
    
    private void atualizaTabela(UUID id) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        if (listaPontos.isEmpty()) {
            return;
        }
        
        Collections.sort(listaPontos, Comparator.comparing(Ponto::getDia));
        
        for (Ponto p : listaPontos){
            adicionaNaTabela(p);
        }

    }
    
    private void getPontoAtual(){
        
        for(Ponto p : listaPontos){
            if(p.getDia().equals(diaHoje)){
              pontoAtual = p;  
            }
        }
    }
    
    private void atualizaLabels(){
        
        String en1 = pontoAtual.getEntrada1() == null ? "" : pontoAtual.getEntrada1().toString();
        String sa1 = pontoAtual.getSaida1() == null ? "" : pontoAtual.getSaida1().toString();
        String en2 = pontoAtual.getEntrada2() == null ? "" : pontoAtual.getEntrada2().toString();
        String sa2 = pontoAtual.getSaida2() == null ? "" : pontoAtual.getSaida2().toString();
        
        jLabelDiaAtual.setText(diaHoje.toString());
        jLabelEntrada1.setText("Entrada1: " + en1);
        jLabelEntrada2.setText("Entrada2: " + en2);
        jLabelSaida1.setText("Saida1: " + sa1);
        jLabelSaida2.setText("Saida2: " + sa2);
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarPonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDiaAtual;
    private javax.swing.JLabel jLabelEntrada1;
    private javax.swing.JLabel jLabelEntrada2;
    private javax.swing.JLabel jLabelSaida1;
    private javax.swing.JLabel jLabelSaida2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
